-- ============================================================
-- F&B Shift + Attendance + Payroll System
-- Supabase / PostgreSQL - V2
--
-- Dùng cho PROJECT MỚI. Không chạy đè lên 01_schema.sql cũ nếu
-- database hiện tại đã có dữ liệu. Với database cũ, cần migration riêng.
--
-- Thiết kế V2:
--   users                : hồ sơ + quyền + device_pin
--   roles_rates          : lương giờ + phụ cấp/ca
--   shifts               : lịch/ca nhân viên đăng ký
--   attendance_punches   : dữ liệu QUẸT THÔ từ máy chấm công (audit)
--   attendance_logs      : dữ liệu ĐÃ GHÉP thành tối đa 2 cặp vào/ra/ngày
--   leave_requests       : đơn nghỉ
--   daily_notes          : NOTE + khoản điều chỉnh theo ngày
--   v_payroll_days       : view dùng chung cho PWA + Excel
--
-- Quy tắc payroll:
--   GIỜ CÔNG = (Ra1 - Vào1) + (Ra2 - Vào2)
--   LƯƠNG NGÀY = GIỜ CÔNG * LƯƠNG GIỜ + PHỤ CẤP
--   TỔNG THU NHẬP = LƯƠNG THÁNG - tổng NOTE dương
--   NOTE âm = cộng bù
--
-- Quan trọng: payroll dùng giờ CHẤM CÔNG THỰC TẾ. Ca đã duyệt nhưng
-- chưa có attendance không tự động tạo giờ công/lương; quản lý có thể
-- sửa attendance sau ở phase tiếp theo.
-- ============================================================

create extension if not exists pgcrypto;

-- =========================
-- 1. USERS / HRM
-- =========================
create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  emp_code text unique not null,
  full_name text not null,
  phone text unique,
  position text,
  role text not null default 'employee'
    check (role in ('employee','manager')),
  device_pin text unique,
  bank_name text,
  bank_account_no text,
  bank_account_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.roles_rates (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  hourly_rate numeric(12,0) not null default 0 check (hourly_rate >= 0),
  allowance_per_shift numeric(12,0) not null default 0 check (allowance_per_shift >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- 2. SHIFT REGISTRATION
-- =========================
create table public.shifts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  work_date date not null,
  check_in_1 time,
  check_out_1 time,
  check_in_2 time,
  check_out_2 time,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, work_date),
  check ((check_in_1 is null and check_out_1 is null) or (check_in_1 is not null and check_out_1 is not null)),
  check ((check_in_2 is null and check_out_2 is null) or (check_in_2 is not null and check_out_2 is not null))
);

-- =========================
-- 3. RAW ATTENDANCE PUNCHES
-- =========================
create table public.attendance_punches (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  device_id text not null,
  device_pin text not null,
  punched_at timestamptz not null,
  verify_type text,
  raw_status text,
  created_at timestamptz not null default now(),
  unique (device_id, device_pin, punched_at)
);

create index attendance_punches_user_time_idx
  on public.attendance_punches(user_id, punched_at);

create index attendance_punches_device_pin_time_idx
  on public.attendance_punches(device_id, device_pin, punched_at);

-- =========================
-- 4. DAILY ATTENDANCE SUMMARY
-- =========================
-- Một dòng / nhân viên / ngày, đã ghép tối đa 2 cặp vào-ra.
-- Bảng này là lớp trung gian để frontend và Excel đọc nhanh.
create table public.attendance_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  work_date date not null,
  device_id text,
  check_in_1 time,
  check_out_1 time,
  check_in_2 time,
  check_out_2 time,
  punch_count integer not null default 0 check (punch_count >= 0),
  source text not null default 'device'
    check (source in ('device','manual','adjusted')),
  synced_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, work_date)
);

create index attendance_logs_date_idx
  on public.attendance_logs(work_date);

-- =========================
-- 5. LEAVE REQUESTS
-- =========================
create table public.leave_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  leave_date date not null,
  reason text,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  approved_by uuid references public.users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index leave_requests_date_status_idx
  on public.leave_requests(leave_date, status);

-- =========================
-- 6. DAILY NOTE / ADJUSTMENT
-- =========================
-- adjustment_amount > 0  => TRỪ tiền
-- adjustment_amount < 0  => CỘNG/bù tiền
create table public.daily_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  note_date date not null,
  note_text text,
  adjustment_amount numeric(12,0) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, note_date)
);

create index daily_notes_user_date_idx
  on public.daily_notes(user_id, note_date);

-- =========================
-- 7. UPDATED_AT TRIGGER
-- =========================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_roles_rates_updated_at on public.roles_rates;
create trigger trg_roles_rates_updated_at
before update on public.roles_rates
for each row execute function public.set_updated_at();

drop trigger if exists trg_shifts_updated_at on public.shifts;
create trigger trg_shifts_updated_at
before update on public.shifts
for each row execute function public.set_updated_at();

drop trigger if exists trg_attendance_logs_updated_at on public.attendance_logs;
create trigger trg_attendance_logs_updated_at
before update on public.attendance_logs
for each row execute function public.set_updated_at();

drop trigger if exists trg_leave_requests_updated_at on public.leave_requests;
create trigger trg_leave_requests_updated_at
before update on public.leave_requests
for each row execute function public.set_updated_at();

drop trigger if exists trg_daily_notes_updated_at on public.daily_notes;
create trigger trg_daily_notes_updated_at
before update on public.daily_notes
for each row execute function public.set_updated_at();

-- =========================
-- 8. MANAGER HELPER
-- =========================
create or replace function public.is_manager()
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.users
    where id = (select auth.uid())
      and role = 'manager'
      and is_active = true
  );
$$;

revoke all on function public.is_manager() from public;
grant execute on function public.is_manager() to authenticated;

-- =========================
-- 9. PAYROLL VIEW
-- =========================
-- security_invoker = true là bắt buộc để view tôn trọng RLS của các bảng nguồn.
create or replace view public.v_payroll_days
with (security_invoker = true)
as
with keys as (
  select user_id, work_date
  from public.shifts
  where status = 'approved'
),
base as (
  select
    u.id as user_id,
    u.emp_code,
    u.full_name,
    u.position,
    coalesce(r.hourly_rate, 0) as hourly_rate,
    coalesce(r.allowance_per_shift, 0) as allowance_per_shift,
    k.work_date,
    a.check_in_1,
    a.check_out_1,
    a.check_in_2,
    a.check_out_2,
    n.note_text,
    coalesce(n.adjustment_amount, 0) as adjustment_amount
  from keys k
  join public.users u on u.id = k.user_id
  left join public.roles_rates r on r.user_id = u.id
  left join public.attendance_logs a
    on a.user_id = k.user_id and a.work_date = k.work_date
  left join public.daily_notes n
    on n.user_id = k.user_id and n.note_date = k.work_date
)
select * from base;

-- =========================
-- 10. APPROVED LEAVE => REJECT SHIFT
-- =========================
create or replace function public.on_leave_approved()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    new.approved_by := (select auth.uid());
    new.approved_at := now();

    update public.shifts
       set status = 'rejected',
           updated_at = now()
     where user_id = new.user_id
       and work_date = new.leave_date
       and status <> 'rejected';

  end if;
  return new;
end;
$$;

drop trigger if exists trg_leave_approved on public.leave_requests;
create trigger trg_leave_approved
before update on public.leave_requests
for each row execute function public.on_leave_approved();

-- =========================
-- 11. LOGIN IDENTIFIER RESOLVER
-- =========================
-- Frontend dùng mã NV hoặc số điện thoại -> backend/auth email ảo.
create or replace function public.resolve_login(identifier text)
returns text
language sql
security definer
stable
set search_path = ''
as $$
  select lower(emp_code) || '@company.local'
  from public.users
  where is_active = true
    and (
      lower(emp_code) = lower(trim(identifier))
      or phone = trim(identifier)
    )
  limit 1;
$$;

revoke all on function public.resolve_login(text) from public;
grant execute on function public.resolve_login(text) to anon, authenticated;

-- =========================
-- 12. ROW LEVEL SECURITY
-- =========================
alter table public.users enable row level security;
alter table public.roles_rates enable row level security;
alter table public.shifts enable row level security;
alter table public.attendance_punches enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.leave_requests enable row level security;
alter table public.daily_notes enable row level security;

-- Xóa policy cũ khi chạy lại file trên project mới / dev database.
drop policy if exists users_read on public.users;
drop policy if exists users_insert on public.users;
drop policy if exists users_update_manager on public.users;
drop policy if exists users_delete_manager on public.users;

create policy users_read
on public.users for select to authenticated
using (id = (select auth.uid()) or (select public.is_manager()));

create policy users_insert
on public.users for insert to authenticated
with check ((select public.is_manager()));

create policy users_update_manager
on public.users for update to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

create policy users_delete_manager
on public.users for delete to authenticated
using ((select public.is_manager()));

-- rates
 drop policy if exists rates_read on public.roles_rates;
 drop policy if exists rates_admin on public.roles_rates;
create policy rates_read
on public.roles_rates for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_manager()));
create policy rates_admin
on public.roles_rates for all to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- shifts
 drop policy if exists shifts_read on public.shifts;
 drop policy if exists shifts_insert_employee on public.shifts;
 drop policy if exists shifts_update_employee_pending on public.shifts;
 drop policy if exists shifts_admin on public.shifts;
create policy shifts_read
on public.shifts for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_manager()));
create policy shifts_insert_employee
on public.shifts for insert to authenticated
with check (user_id = (select auth.uid()) and status = 'pending');
create policy shifts_update_employee_pending
on public.shifts for update to authenticated
using (user_id = (select auth.uid()) and status = 'pending')
with check (user_id = (select auth.uid()) and status = 'pending');
create policy shifts_admin
on public.shifts for all to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- raw punches: employee không nên thấy raw device data; manager chỉ đọc.
drop policy if exists attendance_punches_manager_read on public.attendance_punches;
drop policy if exists attendance_punches_manager_all on public.attendance_punches;
create policy attendance_punches_manager_read
on public.attendance_punches for select to authenticated
using ((select public.is_manager()));
create policy attendance_punches_manager_all
on public.attendance_punches for all to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- daily attendance summary
 drop policy if exists attendance_logs_read on public.attendance_logs;
 drop policy if exists attendance_logs_admin on public.attendance_logs;
create policy attendance_logs_read
on public.attendance_logs for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_manager()));
create policy attendance_logs_admin
on public.attendance_logs for all to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- leave requests
 drop policy if exists leave_read on public.leave_requests;
 drop policy if exists leave_insert_employee on public.leave_requests;
 drop policy if exists leave_admin on public.leave_requests;
create policy leave_read
on public.leave_requests for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_manager()));
create policy leave_insert_employee
on public.leave_requests for insert to authenticated
with check (user_id = (select auth.uid()) and status = 'pending');
create policy leave_admin
on public.leave_requests for all to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- notes
 drop policy if exists notes_read on public.daily_notes;
 drop policy if exists notes_admin on public.daily_notes;
create policy notes_read
on public.daily_notes for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_manager()));
create policy notes_admin
on public.daily_notes for all to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- =========================
-- 13. EXPLICIT GRANTS
-- =========================
revoke all on all tables in schema public from anon;

grant select, insert, update on public.users to authenticated;
grant select, insert, update on public.roles_rates to authenticated;
grant select, insert, update on public.shifts to authenticated;
grant select on public.attendance_punches to authenticated;
grant select on public.attendance_logs to authenticated;
grant select, insert, update on public.leave_requests to authenticated;
grant select, insert, update on public.daily_notes to authenticated;
grant select on public.v_payroll_days to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- =========================
-- 14. REALTIME
-- =========================
-- Chạy 1 lần trên project mới.
alter publication supabase_realtime
  add table public.shifts,
             public.leave_requests,
             public.attendance_logs,
             public.daily_notes;

-- =========================
-- 15. CHECKS
-- =========================
-- Kiểm tra nhanh sau khi chạy:
-- select * from public.v_payroll_days limit 20;
-- select * from public.users;
-- select * from public.attendance_logs order by work_date desc limit 20;
