-- ============================================================
-- MIGRATION: existing project using 01_schema.sql -> V2 attendance model
-- Không xoá dữ liệu cũ. Chạy SAU 03_phase3.sql.
-- Sau migration: thay zk_sync_agent.py bằng zk_sync_agent_v2.py.
-- ============================================================

-- 1) Raw punch audit table
create table if not exists public.attendance_punches (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  device_id text not null,
  device_pin text not null,
  punched_at timestamptz not null,
  verify_type text,
  raw_status text,
  created_at timestamptz not null default now(),
  unique (device_id, device_pin, punched_at)
);

create index if not exists attendance_punches_user_time_idx
  on public.attendance_punches(user_id, punched_at);

create index if not exists attendance_punches_device_pin_time_idx
  on public.attendance_punches(device_id, device_pin, punched_at);

-- 2) Add 2-shift daily summary columns to the existing attendance_logs
alter table public.attendance_logs
  add column if not exists check_in_1 time,
  add column if not exists check_out_1 time,
  add column if not exists check_in_2 time,
  add column if not exists check_out_2 time,
  add column if not exists punch_count integer not null default 0,
  add column if not exists source text not null default 'device',
  add column if not exists synced_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 3) Migrate old first pair into the new columns
update public.attendance_logs
set
  check_in_1 = coalesce(check_in_1, (raw_check_in at time zone 'Asia/Ho_Chi_Minh')::time),
  check_out_1 = coalesce(check_out_1, (raw_check_out at time zone 'Asia/Ho_Chi_Minh')::time),
  punch_count = case
    when raw_check_in is null then 0
    when raw_check_out is null then 1
    else 2
  end
where raw_check_in is not null
   or raw_check_out is not null;

-- 4) V2 agent upsert key = (user_id, work_date)
drop index if exists public.attendance_logs_uq;
create unique index if not exists attendance_logs_user_date_uq
  on public.attendance_logs(user_id, work_date);

-- 5) updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_logs_updated_at on public.attendance_logs;
create trigger trg_attendance_logs_updated_at
before update on public.attendance_logs
for each row execute function public.set_updated_at();

-- 6) Secure payroll view with RLS-aware security_invoker.
-- Payroll chỉ lấy ca đã duyệt; attendance thực tế có thì mới tính giờ/lương.
alter view public.v_payroll_days set (security_invoker = true);

create or replace view public.v_payroll_days
with (security_invoker = true)
as
with keys as (
  select user_id, work_date
  from public.shifts
  where status = 'approved'
)
select
  u.id as user_id,
  u.emp_code,
  u.full_name,
  u.position,
  coalesce(r.hourly_rate, 0) as hourly_rate,
  coalesce(r.allowance_per_shift, 0) as allowance_per_shift,
  k.work_date,
  a.check_in_1,
  a.check_out_1,
  a.check_in_2,
  a.check_out_2,
  n.note_text,
  coalesce(n.adjustment_amount, 0) as adjustment_amount
from keys k
join public.users u on u.id = k.user_id
left join public.roles_rates r on r.user_id = k.user_id
left join public.attendance_logs a
  on a.user_id = k.user_id and a.work_date = k.work_date
left join public.daily_notes n
  on n.user_id = k.user_id and n.note_date = k.work_date;

-- 7) Add RLS to raw punches. Agent dùng service_role nên vẫn đồng bộ bình thường.
alter table public.attendance_punches enable row level security;

drop policy if exists attendance_punches_manager_read on public.attendance_punches;
drop policy if exists attendance_punches_manager_all on public.attendance_punches;
create policy attendance_punches_manager_read
on public.attendance_punches for select to authenticated
using ((select public.is_manager()));
create policy attendance_punches_manager_all
on public.attendance_punches for all to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

grant select on public.attendance_punches to authenticated;

-- 8) Approved leave records the manager and rejects same-day shift.
create or replace function public.on_leave_approved()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    new.approved_by := (select auth.uid());
    new.approved_at := now();

    update public.shifts
       set status = 'rejected',
           updated_at = now()
     where user_id = new.user_id
       and work_date = new.leave_date
       and status <> 'rejected';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_leave_approved on public.leave_requests;
create trigger trg_leave_approved
before update on public.leave_requests
for each row execute function public.on_leave_approved();

-- 9) Realtime (safe for existing publication only if tables weren't already added).
-- Chạy từng dòng nếu Supabase báo duplicate_object.
-- alter publication supabase_realtime add table public.attendance_punches;

-- Verification:
-- select column_name, data_type from information_schema.columns
-- where table_schema='public' and table_name='attendance_logs'
-- order by ordinal_position;
-- select * from public.v_payroll_days limit 20;
