-- ============================================================
-- MIGRATION: manager in-app notifications
-- Chạy sau database/01_schema_v2.sql (và các migration cần thiết
-- để database hiện tại tương thích với schema v2).
-- Migration này không thay đổi attendance_punches/attendance_logs.
-- ============================================================

-- The v2 schema already defines public.is_manager(); keep that shared
-- helper and its existing manager-only RLS policies unchanged.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('shift_pending', 'leave_pending')),
  title text not null,
  body text not null,
  ref_table text not null check (ref_table in ('shifts', 'leave_requests')),
  ref_id bigint not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_recipient_created_idx
  on public.notifications (recipient_id, created_at desc);

create index if not exists notifications_unread_recipient_idx
  on public.notifications (recipient_id, created_at desc)
  where is_read = false;

alter table public.notifications enable row level security;

drop policy if exists notifications_read_own on public.notifications;
create policy notifications_read_own
on public.notifications for select to authenticated
using (recipient_id = (select auth.uid()));

drop policy if exists notifications_update_read_own on public.notifications;
create policy notifications_update_read_own
on public.notifications for update to authenticated
using (recipient_id = (select auth.uid()))
with check (recipient_id = (select auth.uid()));

revoke all on public.notifications from public, anon, authenticated;
grant select on public.notifications to authenticated;
grant update (is_read) on public.notifications to authenticated;

create or replace function public.notify_managers_pending_request()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_employee_name text;
  v_type text;
  v_title text;
  v_body text;
begin
  if tg_op = 'UPDATE' then
    if new.status <> 'pending' then
      return new;
    end if;

    if tg_table_name = 'shifts'
       and old.status = 'pending'
       and old.work_date is not distinct from new.work_date
       and old.check_in_1 is not distinct from new.check_in_1
       and old.check_out_1 is not distinct from new.check_out_1
       and old.check_in_2 is not distinct from new.check_in_2
       and old.check_out_2 is not distinct from new.check_out_2 then
      return new;
    end if;

    if tg_table_name = 'leave_requests'
       and old.status = 'pending' then
      return new;
    end if;
  elsif new.status <> 'pending' then
    return new;
  end if;

  select u.full_name
    into v_employee_name
    from public.users as u
   where u.id = new.user_id;

  if tg_table_name = 'shifts' then
    v_type := 'shift_pending';
    v_title := 'Đăng ký ca mới';
    v_body := coalesce(v_employee_name, 'Nhân viên')
      || ' đăng ký ca '
      || to_char(new.work_date, 'DD/MM')
      || case
           when new.check_in_1 is not null and new.check_out_1 is not null
             then ', ' || to_char(new.check_in_1, 'HH24:MI')
               || ' - ' || to_char(new.check_out_1, 'HH24:MI')
           else ''
         end
      || case
           when new.check_in_2 is not null and new.check_out_2 is not null
             then ', ' || to_char(new.check_in_2, 'HH24:MI')
               || ' - ' || to_char(new.check_out_2, 'HH24:MI')
           else ''
         end;
  else
    v_type := 'leave_pending';
    v_title := 'Đơn xin nghỉ mới';
    v_body := coalesce(v_employee_name, 'Nhân viên')
      || ' gửi đơn xin nghỉ ngày '
      || to_char(new.leave_date, 'DD/MM')
      || case
           when nullif(trim(new.reason), '') is not null
             then ': ' || trim(new.reason)
           else ''
         end;
  end if;

  insert into public.notifications (
    recipient_id,
    type,
    title,
    body,
    ref_table,
    ref_id
  )
  select
    u.id,
    v_type,
    v_title,
    v_body,
    tg_table_name,
    new.id
  from public.users as u
  where u.role = 'manager'
    and u.is_active = true;

  return new;
end;
$$;

revoke all on function public.notify_managers_pending_request() from public;
revoke all on function public.notify_managers_pending_request() from anon, authenticated;

drop trigger if exists trg_notify_managers_shift_pending_insert on public.shifts;
create trigger trg_notify_managers_shift_pending_insert
after insert on public.shifts
for each row
execute function public.notify_managers_pending_request();

drop trigger if exists trg_notify_managers_shift_pending_update on public.shifts;
create trigger trg_notify_managers_shift_pending_update
after update of status, work_date, check_in_1, check_out_1, check_in_2, check_out_2
on public.shifts
for each row
execute function public.notify_managers_pending_request();

drop trigger if exists trg_notify_managers_leave_pending_insert on public.leave_requests;
create trigger trg_notify_managers_leave_pending_insert
after insert on public.leave_requests
for each row
execute function public.notify_managers_pending_request();

drop trigger if exists trg_notify_managers_leave_pending_update on public.leave_requests;
create trigger trg_notify_managers_leave_pending_update
after update of status
on public.leave_requests
for each row
execute function public.notify_managers_pending_request();

-- Enable INSERT events for Supabase Realtime.
-- This block is idempotent; run it as part of this migration on the TEST DB.
do $$
begin
  if not exists (
    select 1
      from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end;
$$;
